#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: false
packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin

write_files:
  - path: /home/ubuntu/myscript.sh
    permissions: '0755'
    owner: ubuntu:ubuntu
    content: |
      #!/bin/bash
      cd /home/ubuntu
      git clone https://github.com/DioRoman/shvirtd-example-python.git
      mv shvirtd-example-python /opt
      docker compose -f /opt/shvirtd-example-python/compose.yaml -f /opt/shvirtd-example-python/proxy.yaml up -d

runcmd:
  - /home/ubuntu/myscript.sh
